### ISSUE TITLE
Hibernate support

### ISSUE THREAD

**Issue by NeoCortex97** [fujaba/fulib#106]
Hi, it would be really really cool, if fulib had support for generating orm-annotations like Hibernate annotations, so the Model-classes could be perssisted directly to a database.

**To be honest:**
I did not look at the Tables feature of fulib! If `fulib-tables` has enough orm capabilities for basic applications, I would love to use it. Otherwise a hint where and how I could hook into the code generation to implement adding the annotations myself.

*And in german too:*
Hi,
Ich würde es sehr begrüßen wenn es möglich wäre bei der Generierung der Modellklassen direkt ORM-Annotations wie bspw. Hibernate mit generieren zu können. Zumindest die ganzen Beziehungen müssten sich ja relativ leicht mappen lassen, da fulib ja bereits die Information zu den Beziehungen zwischen Modellen bereits enthält.

**Um ehrlich zu sein:**
Ich habe mir `fulib-tables` noch nicht angesehen, dem namen nach könnte es allerdings einige Dinge bereits enthalten, die ich von einem ORM brauche. Wenn die Features davon bereits ausrechen würden am Ende relativ einfach mit einer DAtenbank reden zu können, wäre es großartig.
Ansonsten würde ich mich sehr freuen, wenn ich einen hinweis bekäme an welcher Stelle man sich in die Generierung einklinken muss, um das Hinzufügen der Annotations selbst implementierne zu können.

**Comment by Clashsoft** [comment]
Hibernate annotations can be added to the generated code without problems. We do not plan to add first-class support for specific libraries, that is out of score for this project.
