### ISSUE TITLE
Protobuf generation

### ISSUE THREAD

**Issue by NeoCortex97** [fujaba/fulib#107]
Would it be possible to automagically generate protobuf definitions?
I would like to serialize and deserialize Objects with protobuf to persist objects to disk.

Where do I have to hook into fulib to get the required model info?

**Comment by Clashsoft** [comment]
You could hook into the ClassModelDecorator to inspect the ClassModel and create your own code generation from there.

**Comment by NeoCortex97** [comment]
Thanks, I will try that. Would you like to get a pull-request, or link the repo if I manage to get a working version?
I can image that someone else might want to use it as well.

**Comment by Clashsoft** [comment]
Yes, feel free to make a PR or link.
