### ISSUE TITLE
RemoveYou does not work correctly for subclasses

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulib#15]
# Problem Example

Consider the following example:

```java
final Clazz war = mb.haveClass("War");
final Clazz gameObject = mb.haveClass("GameObject");
final Clazz shroom = mb.haveClass("Shroom");

mb.haveSuper(shroom, gameObject);

mb.haveRole(war, "gameObjects", MANY, gameObject, "war", ONE);
```

```java
War war = new War();
Shroom shroom = new Shroom();

war.withGameObjects(shroom);

FulibTools.objectDiagrams().dumpPng("tmp/before.png", war);
```

![before](https://user-images.githubusercontent.com/4145923/70225167-d19f7e00-174e-11ea-9512-adb67c93bb57.png)

```java
shroom.removeYou();

FulibTools.objectDiagrams().dumpPng("tmp/after.png", war);
```

![after](https://user-images.githubusercontent.com/4145923/70225187-dc5a1300-174e-11ea-84eb-fbbdce32781b.png)

```java
assertThat(war.getGameObjects(), CoreMatchers.hasItem(shroom));
```

# Potential Fix

I believe the fix is as simple as generating a call to `super.removeYou()` within the body of `Shroom#removeYou()`. In general, every class with a super-class should have such a call in it's removeYou method.

Two special cases are to be taken care of:

1. if the subclass has no associations, it would not receive a removeYou method, so there is no place to insert the super call.
2. if *all* superclasses (i.e., the direct superclass and its transitive superclasses) have no associations, then there is no super method to call. More precisely, it is not enough to check the direct superclass for associations, because any ancestor could have some, in which case we would need to generate the removeYou method.

**Comment by azuendorf** [comment]
fixed.
