### ISSUE TITLE
Typesafe with and without methods

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulib#20]
Replace the old varargs `with(Object...)` and `without(Object...)` methods with typesafe overloads (analogous for `without`):

- `with(Foo)` - single item is a very common case, and shouldn't have to pay array creation overhead introduced by varargs.
- `with(Foo...)` - varargs becomes typesafe
- `with(Collection<? extends Foo>)` - allows collections to be added. Note how `? extends` is used, which is currently unsupported by the `Parser`, so this depends on #17.

This feature is currently being worked on in the [`typesafe-with`](https://github.com/fujaba/fulib/tree/typesafe-with) branch.

**Comment by Clashsoft** [comment]
@azuendorf should we keep generating the `with(Object...)` and `without(Object...)` methods for associations for backward compatibility? For attributes it's not necessary since multi-attributes are new.

**Comment by azuendorf** [comment]
I don't think so. 
Usally, the people have already used parameters of the correct type and the new with methods will work for them.
