### ISSUE TITLE
Omit unnecessary methods

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulib#21]
- subclasses don't need additional property change methods and fields.
- classes without associations don't need `removeYou`.

**Comment by azuendorf** [comment]
Well, when a class gets a super class or association or it looses a super class or association, 
the code generator would have to add or remove the removeYou methods. 
This adds a lot of complexity to the code generator which eventually is error prone. 
For the listeners, the additional methods are not that much a problem. However, the extra listeners 
attribute hurts. 
I am not sure.

**Comment by Clashsoft** [comment]
Perhaps a default superclass shared by all method classes could solve this problem?

```java
class ModelObject
{
   private PropertyChangeSupport listeners;

   public boolean addPropertyChangeListener(PropertyChangeListener listener) { ... }

   public boolean addPropertyChangeListener(String propertyName, PropertyChangeListener listener) { ... }

   public boolean removePropertyChangeListener(PropertyChangeListener listener) { ... }

   public boolean removePropertyChangeListener(String propertyName, PropertyChangeListener listener) { ... }

   public boolean firePropertyChange(String propertyName, Object oldValue, Object newValue) { ... }

   public void removeYou()
   {
   }
}
```

With it:

- we never have to generate property change methods in any other class, which greatly reduces clutter
- we can always generate `super.removeYou()` and never have to worry about breaking things when superclasses change
- one can implement APIs that operate on any `ModelObject`, e.g. to work with property change events. E.g.:
 
```java
class PropertyChangePrinter implements PropertyChangeListener
{
   public void install(ModelObject obj)
   {
      obj.addPropertyChangeListener(this);
   }

   @Override
   public void propertyChange(PropertyChangeEvent evt)
   {
      if (evt.getOldValue() instanceof ModelObject)
      {
         ((ModelObject) evt.getOldValue()).removePropertyChangeListener(this));
      }
      if (evt.getNewValue() instanceof ModelObject)
      {
         ((ModelObject) evt.getNewValue()).addPropertyChangeListener(this));
      }
      System.out.println(evt);
   }
}
```

**Comment by azuendorf** [comment]
We have had that. No good. Users hate it, when there is already a root class you have to inherit from. 
Many Frameworks use this idea and if you would like to use model objects with such a framework, you are screwed. 
So I do not like this idea at all. I would rather go with the complicated code generator that covers the various situations.
