### ISSUE TITLE
ClassModelManager::associate accepts conflicting role names

### ISSUE THREAD

**Issue by azuendorf** [fujaba/fulib#28]
mm.associate(customer, "orders", MANY, order, "customer", ONE);
      mm.associate(product, "orders", MANY, order, "customer", ONE);

produces two setCustomer methods within class order, one with a param type customer
and one with parameter type order. 

When the reverse direction calls setCustomer(null) it cannot be resolved :)

**Comment by Clashsoft** [comment]
What would be the expected behaviour (of the `associate`) method? Should it delete the old `orders` role plus the reverse role? Or throw an exception?
