### ISSUE TITLE
Cannot generate methods with generic return type

### ISSUE THREAD

**Issue by azuendorf** [fujaba/fulib#34]
**To Reproduce**

```java
declaration = "public <T extends Object> T getModelObject(String id)";
body = "   return (T) idMap.get(id);\n";
mm.haveMethod(editor, declaration, body);
```

generates 

```java
public <T extends(String id) { 
   return (T) idMap.get(id);
}
```

**Expected behavior**

It should generate 

```java
public <T extends Object> T getModelObject(String id) {
   return (T) idMap.get(id);
}
```

**Comment by Clashsoft** [comment]
As of fulib v1.2, `FMethod` should correctly parse the name and parameters from the declaration, but it ignores the type parameters. So the output should be what you put unter "expected behaviour". But don't you want the generic type parameters, too?
