### ISSUE TITLE
Consistent documentation

### ISSUE THREAD

**Issue by ulno** [fujaba/fulib#38]
**Is your feature request related to a problem? Please describe.**
There is nearly no documentation - some small examples, but nothing to help one to get started or explaining why fulib exists and what it is good for or which problem it solves. No guidance where to start and also no explicit link to https://www.fulib.org/ or back.

**Describe the solution you'd like**
At least open up some TODOs and tasks (where are the todo tasks btw.?) regarding documentation.

I am going to teach systems modeling in Tartu, Estonia in September and it would be a good opportunity to making use of fulib in this class.

**Comment by azuendorf** [comment]
I added some reference to www.fulib.org for more documentation. 
What else would you like to have?

**Comment by Clashsoft** [comment]
@azuendorf FYI, I also started moving and rewording some stuff on the `docs` branch.

**Comment by ulno** [comment]
It would for example be nice to have several tutorials for teachers and students to get started with fulib, especially important would be to see the transition from the website to a local IntelliJ installation (on Mac, Windows, and Linux).

**Comment by Clashsoft** [comment]
I did some work on the documentation and it should be at least somewhat better now. It is available on both GitHub Pages (https://fujaba.github.io/fulib/docs and https://fujaba.github.io/fulibScenarios/docs) and on fulib.org (currently a prototype - https://dev.fulib.org/docs)
